name: "docker launchable actions"
description: "sample launchable actions"
author: "launchableinc"
inputs:
  source:
    required: true
    description: "build source"
    default: "."
  test_runner:
    required: true
    description: "test runner name"
    default: "go-test"
  report:
    required: true
    description: "test report file path"
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/bin/bash"
  args:
    - -c
    - "launchable verify; launchable record build --name $GITHUB_RUN_ID --source ${{ inputs.source }}; launchable record tests --build $GITHUB_RUN_ID ${{ inputs.test_runner }} ${{ inputs.report }}"
