requires 'perl', '5.008001';

on 'test' => sub {
    requires 'Test::More', '0.98';
    requires 'Test2::V0';
    requires 'TAP::Formatter::JUnit', git => 'https://github.com/shibuiwilliam/TAP-Formatter-JUnit.git';
};

