load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "mylib_test1",
    srcs = [
        "MyLibTest1.java",
    ],
    test_class = "com.ninjinkun.MyLibTest1",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test2",
    srcs = [
        "MyLibTest2.java",
    ],
    test_class = "com.ninjinkun.MyLibTest2",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test3",
    srcs = [
        "MyLibTest3.java",
    ],
    test_class = "com.ninjinkun.MyLibTest3",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)


java_test(
    name = "mylib_test4",
    srcs = [
        "MyLibTest4.java",
    ],
    test_class = "com.ninjinkun.MyLibTest4",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test5",
    srcs = [
        "MyLibTest5.java",
    ],
    test_class = "com.ninjinkun.MyLibTest5",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test6",
    srcs = [
        "MyLibTest6.java",
    ],
    test_class = "com.ninjinkun.MyLibTest6",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test7",
    srcs = [
        "MyLibTest7.java",
    ],
    test_class = "com.ninjinkun.MyLibTest7",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test8",
    srcs = [
        "MyLibTest8.java",
    ],
    test_class = "com.ninjinkun.MyLibTest8",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)

java_test(
    name = "mylib_test9",
    srcs = [
        "MyLibTest9.java",
    ],
    test_class = "com.ninjinkun.MyLibTest9",
    deps = [
        "//src/main/java/com/ninjinkun:mylib",
    ],
)
