name: "composite action record test"
description: "sample composite action"
author: "launchbleinc"
inputs:
  python-version:
    required: true
    description: "Python version"
    default: "3.10"
  build_name:
    required: true
    description: "build name"
    default: ""
  test_runner:
    required: true
    description: "test runner name"
    default: "go-test"
  report:
    required: true
    description: "test report file path"
    default: "."
runs:
  using: "composite"
  steps:
    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: install
      shell: bash
      run: pip install launchable
    - id: "record test"
      shell: bash
      run: |
        launchable record tests --build ${{ inputs.build_name }} ${{ inputs.test_runner }} ${{ inputs.report }}
