name: "composite action record test"
description: "sample composite action"
author: "launchbleinc"
inputs:
  python-version:
    required: false
    description: "Python version >= 3.5. Default 3.10"
    default: "3.10"
  source:
    required: false
    description: "Path to a local Git repository/workspace. Default current directory."
    default: "."
  max_days:
    required: false
    description: "The maximum number of days to collect commits retroactively. Default 30."
    default: "30"
  no_submodules:
    required: false
    description: "Stop collecting build information from Git Submodules. Default False."
  test_runner:
    required: true
    description: "test runner name"
  report:
    required: true
    description: "The test report file path. Defaul ..."
    default: "."
runs:
  using: "composite"
  steps:
    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: install
      shell: bash
      run: pip install launchable
    - id: verify
      shell: bash
      run: |
        launchable verify
    - id: record_build
      shell: bash
      run: |
        launchable record build \
          --name $GITHUB_RUN_ID \
          --max-days ${{ inputs.max_days }} \
          --source ${{ inputs.source }}
    - id: record_test
      shell: bash
      run: |
        launchable record tests \
          --build $GITHUB_RUN_ID \
          ${{ inputs.test_runner }} \
          ${{ inputs.report }}
