name: Go

on:
  push:
    branches: [master]
    paths:
      - "go/**"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "go/**"
      - ".github/workflows/go.yml"

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_GO }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: master
          fetch-depth: 0
          path: servicehub
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          repository: launchableinc/cli
          ref: main
          path: taf-utilities
          fetch-depth: 0
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          repository: golang/go
          ref: go1.18.10
          path: digital-workshop
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Set up
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          sudo apt-get update && sudo apt-get install -y wget
          sudo apt-get update && sudo apt-get install -y golang-go
          sudo apt install -y default-jre
          sudo apt install -y default-jdk
          java --version
          python -m pip install --upgrade pip
          python3 -m pip install requests
          python -m pip install launchable
           go install github.com/jstemmer/go-junit-report@latest
      - name: Session
        run:  |
          launchable verify
          pwd
          ls -la
          launchable record build --source src=./servicehub --name $GITHUB_RUN_ID
      - name: Test
        run: |
          cd servicehub/go
          launchable record session --build $GITHUB_RUN_ID
          go test -list="Test|Example" ./... | launchable subset --confidence 80%  go-test > launchable-subset.txt
          go test $(cat launchable-subset.txt) ./... -v 2>&1 | $HOME/go/bin/go-junit-report -set-exit-code > report.xml
          launchable record tests go-test report.xml
      - name: Record
        run: launchable record tests go-test report.xml
        if: always()
