name: Go composite

on:
  push:
    branches: [main]
    paths:
      - "go/**"
  pull_request:
    paths:
      - "go/**"

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_GO }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install dependencies
        run: |
          go install github.com/jstemmer/go-junit-report@latest
      - name: Test
        run: go test -v ./... 2>&1 | go-junit-report -set-exit-code > report.xml
      - name: Record
        uses: ./go/composite_action_record_test
        with:
          source: .
          test_runner: go-test
          report: ./go/
        if: always()