name: Efficient pull request validation for Gradle example

on:
  pull_request:
    paths:
    - gradle/**
  push:
    paths:
    - gradle/**

env:
  LAUNCHABLE_ORGANIZATION: "self-org"
  LAUNCHABLE_WORKSPACE: "nexe"
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_GO }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run tests with Gradle and Launchable
      run: ./pre-merge.sh
      working-directory: ./gradle
      env:
        GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
