name: Test Maven sample

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_MAVEN }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

on:
  push:
    branches:
      - master
    paths:
      - maven/**
      - .github/workflows/maven.yaml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: maven
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: "temurin"
      - name: Install dependencies
        run: pip install launchable
      - run: "launchable verify"
      - name: Record commits and build
        run: 'launchable record build --name "$GITHUB_RUN_ID" --source ..' # care for working-directory path
      - name: "Subset and Test - Windows"
        if: matrix.os == 'windows-latest'
        run: |
          launchable record session --build $env:GITHUB_RUN_ID > session.txt
          mvn test-compile
          $session = Get-Content session.txt
          launchable subset --session $session --target 80% maven --scan-test-compile-lst > launchable-subset.txt
          mvn test "-Dsurefire.includesFile=launchable-subset.txt"
      - name: "Subset and Test - Linux"
        if: matrix.os == 'ubuntu-latest'
        run: |
          launchable record session --build $GITHUB_RUN_ID > session.txt
          mvn test-compile
          launchable subset --session $(cat session.txt) --target 80% maven --scan-test-compile-lst > launchable-subset.txt
          mvn test -Dsurefire.includesFile=launchable-subset.txt
      - name: "Record - Windows"
        if: matrix.os == 'windows-latest' && always()
        run: |
          $session = Get-Content session.txt
          launchable record tests --session $session maven "./**/target/surefire-reports/"
      - name: "Record - Linux"
        if: matrix.os == 'ubuntu-latest' && always()
        run: |
          launchable record tests --session $(cat session.txt) maven "./**/target/surefire-reports/"
