name: Test Maven sample

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_MAVEN }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

on:
  push:
    branches:
      - master
      - add-maven-example # for debug
    paths:
      - maven/**
      - .github/workflows/maven.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: maven
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: "temurin"
      - name: Install dependencies
        run: pip install launchable
      - run: "launchable verify"
      - name: Record commits and build
        run: 'launchable record build --name "$GITHUB_RUN_ID" --source ..' # care for working-directory path
      - name: Subset
        run: |
          mvn test-compile
          launchable subset --target 80% maven --scan-test-compile-lst > launchable-subset.txt
      - name: Test
        run: mvn test -Dsurefire.includesFile=launcahble-subset.txt
      - name: Record
        run: launchable record tests maven ./**/target/surefire-reports/
        if: always()
