name: PyTest

on:
  push:
    branches: [master]
    paths:
      - "pytest/**"
  pull_request:
    paths:
      - "pytest/**"

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_PYTEST }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: pytest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: launchable verify
      - name: Run Pytest
        run: |
          launchable record build --name ${GITHUB_RUN_ID}
          launchable record session --build ${GITHUB_RUN_ID} --test-suite pytest > session.txt

          pytest tests/test.py --collect-only -q > test_list.txt
          cat test_list.txt | launchable subset --session $(cat session.txt) --target 100% pytest > launchable-subset.txt

          function record() {
            # Record test results
            launchable record tests --session $(cat session.txt) pytest --json test-results/results.json
          }
          trap record EXIT

          pytest --report-log=test-results/results.json $(cat launchable-subset.txt)

