name: PyTest

on:
  push:
    branches: [master]
    paths:
      - "pytest/**"
  pull_request:
    paths:
      - "pytest/**"

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_PYTEST }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: pytest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==4.2.0 attrs==19.1.0 pytest-launchable
      - run: launchable verify
      - name: Run Pytest
        run: pytest --launchable .
